Add dir path and ignore option
incu6us/goimports-reviser pull request #61
Opened 2021-09-16 13:13 UTC by suyanlong

goimports-reviser -dir-path ./  -project-name github.com/incu6us/goimports-reviser  -ignore v2 -format -rm-unused

2021-09-16 13:35 UTC, incu6us requested changes

2021-09-16 13:35 UTC, incu6us commented on .gitignore
> +.idea
remove it. you can put it to global ignore file and leave project ignore file clear as much as possible

2021-09-16 13:35 UTC, incu6us commented on main.go
> +	do := func(filePath string) {
do what? move it from anonymous func and rename it

2021-09-16 13:35 UTC, incu6us commented on pkg/astutil/testdata/testdata.go
> +//go:build test
format for this is `// +build test` and it is already present

2021-09-16 13:35 UTC, incu6us commented on main.go
> +func PWD() string {
is it really need to have publicly?

2021-09-16 13:35 UTC, incu6us commented on main.go
> +func IsDir(p string) bool {
public?

2021-09-16 13:35 UTC, incu6us commented on main.go
> +func IsIgnore(path string) bool {
public?

2021-09-16 13:35 UTC, incu6us commented on main.go
> +	// if err := validateRequiredParam(filePath); err != nil {
if it is not needed, you can remove it

2021-09-16 13:35 UTC, incu6us commented on main.go
> +	// if err := validateRequiredParam(filePath); err != nil {
but I believe it is needed

2021-09-16 13:35 UTC, incu6us commented on main.go
> +var ignore string // 忽略指定的目录
why it is placed separated? all params are defined on 46 line

2021-09-16 13:35 UTC, incu6us commented on main.go
> +	ignoreArg              = "ignore"
ignore what? naming should be clear for understanding

2021-09-16 13:35 UTC, incu6us commented on Makefile
> +	@goimports-reviser -dir-path ./  -project-name github.com/incu6us/goimports-reviser  -ignore v2 -format -rm-unused
ignore what?

2021-09-18 01:20 UTC, suyanlong commented
@incu6us thanks you for review, now,let's again review.

2022-08-03 19:54 UTC, incu6us commented
done in version v3.1.0

2022-08-03 19:54 UTC, closed without merging